
[site]
url = "https://o11y.cn"
name = "O11Y 杂志"
description = "专注于可观测性的独立开源技术杂志"
locale = "zh"
menu = [
  { name = "关于", url = "/about" },
  { name = "GitHub", url = "https://github.com/zineland/o11y" },
]

[authors]

[theme]

[[issue]]
slug = "1"
number = 1
title = "第一期"
path = "content/issue-1"
