
[site]
url = "https://o11y.cn"
name = "O11Y 杂志"
description = "专注于可观测性领域的独立开源技术杂志"
locale = "zh"
menu = [
  { name = "关于", url = "/about" },
  { name = "GitHub", url = "https://github.com/zineland/o11y" },
]

[authors]
folyd = { avatar = "/static/avatar/folyd.jpg", editor = true, bio = "" }

[theme]
primary_color = "#c3e8ff"
secondary_color = "#faf8f3"
main_color = "#674646"
link_color = "#36a5ea"
background_image = "/static/bg.svg"
head_template = "templates/head.html"
footer_template = "templates/footer.html"

[[issue]]
slug = "1"
number = 1
title = "第一期"
path = "content/issue-1"
