
[[article]]
slug = "opentelemetry"
file = "1-opentelemetry.md"
title = "Opentelemetry 的前世今生"
author = "Folyd"
cover = "/static/1/opentelemetry.png"
pub_date = "2022-05-06"
publish = true
featured = true
